# Generated by Django 2.0.5 on 2018-06-05 20:14

from django.db import migrations, models
import django.db.models.deletion
import liberty.models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty', '0002_auto_20180604_2057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liberty.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(verbose_name='Кiлькiсть'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='book',
            name='lib_id',
            field=models.CharField(max_length=200, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=liberty.models.get_image_path, verbose_name='Обкладинка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='bookstudent',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liberty.Book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookstudent',
            name='count',
            field=models.IntegerField(verbose_name='Кiлькiсть'),
        ),
        migrations.AlterField(
            model_name='bookstudent',
            name='get_date',
            field=models.DateTimeField(verbose_name='Получил'),
        ),
        migrations.AlterField(
            model_name='bookstudent',
            name='return_date',
            field=models.DateTimeField(verbose_name='Отдал'),
        ),
        migrations.AlterField(
            model_name='bookstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liberty.Student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Факультеты'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liberty.Department', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_entry',
            field=models.DateTimeField(verbose_name='год поступления'),
        ),
    ]
