# Generated by Django 2.0.5 on 2018-06-10 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liberty', '0003_auto_20180605_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Категорію',
                'verbose_name_plural': 'Категорія',
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автора', 'verbose_name_plural': 'Автор'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книжка', 'verbose_name_plural': 'Книжку'},
        ),
        migrations.AlterModelOptions(
            name='bookstudent',
            options={'verbose_name': 'Долг', 'verbose_name_plural': 'Долги'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультет'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студента'},
        ),
        migrations.AddField(
            model_name='book',
            name='caregory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='liberty.Category', verbose_name='Категорія'),
            preserve_default=False,
        ),
    ]
