# Generated by Django 2.0.5 on 2018-06-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liberty', '0004_auto_20180610_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='caregory',
            new_name='category',
        ),
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(default='', upload_to='uploads', verbose_name='Файл книги'),
        ),
    ]
